### ISSUE TITLE
Profil ekranının oluşturulması

### ISSUE THREAD

**Issue by orbingol** [gokhantamkoc/LibApp#3]
Mockuplar gösterilen şekilde profil ekranının oluşturulması. Bu ekran aşağıdaki özellikleri içermelidir.
- Karşılama mesajı
- Ceza miktarı (TL cinsinden)
- İade edilmemiş kitaplar (due books)
- Kütüphaneden alınmış kitap listesi
- Profil menüsü

_Detaylar:_
- Kitap listesi kendi başına alt-üst slide yapabiliyor olmalı.
- Kitap listesi içinde kitap ismi yazan başlıklarda
  *\* Sol tarafta seçim ikonu
  *\* Sağ tarafta basit detayların bulunduğu katmanın aşağı doğru açılması
  *\* Basit detayların olduğu katman açıkken, o katmanın sola doğru kaydırılması kitapların tam detayını göstermeli
- Profi ekranına uygun "Options" menüsünün yapılması

**Comment by fatihbelen** [comment]
profil ekranı için de başlangıç yaptım.
o kısmını ekledim
