### ISSUE TITLE
Arama ekranının oluşturulması

### ISSUE THREAD

**Issue by orbingol** [gokhantamkoc/LibApp#4]
- Arama ekranı "advanced search" olarak çalışacak.
- Sanal klavyede arama tuşu çıkmalı ve butona basılmaya gerek olmamalı
- Sanal klavye arama metin kutusunu ve  arama seçeneklerini kapatmamalı

**Comment by gokhantamkoc** [comment]
Arama ekranı oluşturuldu. Bu arada commit'i yanlış yapmış olabilirim. Çünkü tüm projeyi değil sadece html,css ve js scriptlerini upload ettim.

Oluşturulan Search Ekranındaki eksiklikler:
- Buttonlar responsive design'a uygun tasarlanmadı. 
- Sanal klavyeye "Search" butonu konmadı.
- "Search Input" içerisinde iconlar include etmedim.

**Comment by orbingol** [comment]
Tamam. Bunlar icin issue acalim ve bu konudan linkleyelim. "Github
Markdown" syntax'i ile linkleme yapilabilir.

**Comment by orbingol** [comment]
@gokhantamkoc : jQuery Mobile ile ilgili bir sorun tespit ettim. Dizin yapısını düzenledim. Şu anda ikonlar düzgün görünüyor. Yine de sorunları issue olarak açalım, böylelikle atlamayız.
